server:
  address: 0.0.0.0:8080
  name: app
sentry:
  dsn: ""
mysql: #conf.Init函数会自动创建mysql连接
  address: root:root@tcp(127.0.0.1:3306)/test?charset=utf8&parseTime=True&loc=Local
  maxIdle: 3
  maxOpen: 20
  logMode: false
redis: #conf.Init函数会自动创建redis连接
  address: 127.0.0.1:6379
  password:
  db: 10
  poolSize: 5
session: #conf.InitRedisSession函数会自动创建redis session连接中间件
  name: "demo-session-name" #一般情况不需要填写，项目中有多个session时才需设置
  secret: "asdfafd" #一般情况下不需要配置，默认会自动生成秘钥
  ttl: 86400
  domain: localhost
  address: 127.0.0.1:6379
  password:
  db: 11
  poolSize: 5
api:
  service:
    url: "http://baidu.com"
